stages:
- stage: Test
  jobs:
  - job: ModuleTest
    pool: 
      name: 'vdc-self-hosted'
    steps:
    - task: PowerShell@2
      displayName: "Pester Tests for All Modules"
      inputs:
        filePath: 'orchestration/Tests/UnitTests/AllModules.Tests.ps1'
        pwsh: true