stages:
- stage: Test
  jobs:
  - job: ModuleTest
    pool: 
      name: 'vdc-self-hosted'
    steps:
    - task: PowerShell@2
      displayName: "Pester Tests for All Modules"
      inputs:
        targetType: 'inline'
        script: '# Write your powershell commands here.
          $rootPath = Resolve-Path ".\";
          $resultsFile = Join-Path $rootPath "Test-Pester.XML";
          Get-ChildItem -Path "module.tests.ps1" -Recurse | Select FullName | ForEach-Object { Invoke-Pester -Script $_.FullName -OutputFile $resultsFile };
          
          # Use the environment variables input below to pass secret variables to this script.'
        pwsh: true